
# CONTENEDOR PARA PROBAR EL ENCOLAMIENTO DIRECTAMENTE
# version: "3.9"
# services:
#   web:
#     build: .
#     volumes:
#     - .:/src
#     ports:
#       - "8000:5000"
#     mem_limit: 2000m
#   redis:
#     image: redis
#     container_name: node_challenge_redis
#     restart: on-failure
#     environment:
#       - ALLOW_EMPTY_PASSWORD=yes
#     command: --port 6380
#     ports:
#       - "6380:6380"
#     expose:
#       - "6380"


# CONTENEDOR PARA CREAR CONTENEDOR REDIS
# version: "3.9"
# services:
#   redis:
#     image: redis
#     container_name: my-redis-container
#     ports:
#       - "6379:6379"
#     expose:
#       - "6379"

version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq-container
    ports:
      - "5672:5672" # Puerto para la conexión AMQP
      - "15672:15672" # Puerto para la interfaz de administración web
